services:
  neodash:
    build: .
    container_name: neodash-panel
    restart: always
    # Network Mode Host ist die Lösung für das "Offline"-Problem:
    # Der Container nutzt das Netzwerk des KVMs direkt. 
    network_mode: "host" 
    pid: "host"
    privileged: true
    environment:
      - PANEL_PORT=${PANEL_PORT}
    volumes:
      - ${DATA_PATH}:/app/data
      - ${SERVER_PATH}:/app/servers
